//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tensorflex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LineaAlbaran
    {
        public int Id { get; set; }
        public int AlbaranId { get; set; }
        public int ArticuloId { get; set; }
        public int Cantidad { get; set; }
        public decimal Precio { get; set; }
    
        public virtual Albarán Albarán { get; set; }
        public virtual Articulo Articulo { get; set; }
    }
}
