CREATE TABLE [dbo].[Clientes] (
    [CodigoEmpresa]        SMALLINT      NULL,
    [IdDelegacion]         VARCHAR (10)  NULL,
    [CodigoCliente]        VARCHAR (15)  NULL,
    [SiglaNacion]          VARCHAR (2)   NULL,
    [CifDni]               VARCHAR (13)  NULL,
    [CifEuropeo]           VARCHAR (15)  NULL,
    [FechaAlta]            DATETIME      NULL,
    [CodigoProveedor]      VARCHAR (15)  NULL,
    [CodigoContable]       VARCHAR (15)  NULL,
    [RazonSocial]          VARCHAR (40)  NOT NULL,
    [RazonSocial2]         VARCHAR (40)  NULL,
    [Nombre]               VARCHAR (35)  NOT NULL,
    [Domicilio]            VARCHAR (40)  NULL,
    [Domicilio2]           VARCHAR (40)  NULL,
    [Nombre1]              VARCHAR (30)  NULL,
    [FormadePago]          VARCHAR (35)  NULL,
    [CodigoBanco]          VARCHAR (10)  NULL,
    [CodigoAgencia]        VARCHAR (6)   NULL,
    [DC]                   VARCHAR (2)   NULL,
    [CCC]                  VARCHAR (15)  NULL,
    [IBAN]                 VARCHAR (34)  NULL,
    [CodigoZona]           INT           NULL,
    [CodigoRuta_]          VARCHAR (10)  NULL,
    [CodigoTransportista]  INT           NULL,
    [TipoPortes]           VARCHAR (1)   NULL,
    [ObservacionesCliente] VARCHAR (50)  NULL,
    [Comentarios]          TEXT          NULL,
    [CodigoSigla]          VARCHAR (2)   NULL,
    [ViaPublica]           VARCHAR (40)  NULL,
    [Numero1]              VARCHAR (4)   NULL,
    [Numero2]              VARCHAR (4)   NULL,
    [Escalera]             VARCHAR (2)   NULL,
    [Piso]                 VARCHAR (2)   NULL,
    [Puerta]               VARCHAR (2)   NULL,
    [Letra]                VARCHAR (2)   NULL,
    [CodigoPostal]         VARCHAR (8)   NULL,
    [CodigoMunicipio]      VARCHAR (7)   NULL,
    [Municipio]            VARCHAR (25)  NULL,
    [ColaMunicipio]        VARCHAR (15)  NULL,
    [CodigoProvincia]      VARCHAR (5)   NULL,
    [Provincia]            VARCHAR (20)  NULL,
    [CodigoNacion]         SMALLINT      NULL,
    [Nacion]               VARCHAR (25)  NULL,
    [Telefono]             VARCHAR (15)  NULL,
    [Telefono2]            VARCHAR (15)  NULL,
    [Telefono3]            VARCHAR (15)  NULL,
    [Fax]                  VARCHAR (15)  NULL,
    [Email1]               VARCHAR (250) NULL,
    [HorarioDomicilioLc]   VARCHAR (100) NULL,
    [id] INT IDENTITY (7000,1) NOT NULL, 
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


